import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import packJson from '../../src/packs/night-superintendents-deposition/night-superintendents-deposition.wolfpack.json' with { type: 'json' };
import {
  validatePack,
  digestPack,
  importRecordBundle,
  computeProgress,
} from '../../src/engine/index.js';
import type { WolfRecord } from '../../src/engine/index.js';

// The checked-in demo record is regenerated by scripts/generate-demo-record.mjs.
// These tests keep it importable, keep its provenance honest, and keep it from
// silently drifting away from the published pack.

const BUNDLE_PATH = 'examples/night-superintendent/night-superintendents-deposition.demo.wolfrecord.json';

function loadBundle() {
  return importRecordBundle(JSON.parse(readFileSync(BUNDLE_PATH, 'utf8')));
}

test('the demo record imports through the same validation the app uses', () => {
  const bundle = loadBundle();
  assert.equal(bundle.recordId, 'b6d1c3a9-52f4-4e08-9a7d-31c85e2f9b04');
  assert.equal(bundle.status, 'active');
});

test('the demo record declares its subject fictional in exported metadata', () => {
  const bundle = loadBundle();
  assert.match(bundle.subject.subtitle ?? '', /fictional/i);
  assert.match(bundle.subject.organization ?? '', /fictional/i);
});

test('the pack snapshot matches the published pack and the digest is genuine', async () => {
  const bundle = loadBundle();
  const published = validatePack(packJson);
  assert.deepEqual(bundle.pack.snapshot, published);
  assert.equal(bundle.pack.packDigest, await digestPack(bundle.pack.snapshot));
});

test('every response targets a snapshot prompt and revision chains link correctly', () => {
  const bundle = loadBundle();
  const promptIds = new Set(bundle.pack.snapshot.prompts.map((p) => p.id));
  for (const response of bundle.responses) {
    assert.ok(promptIds.has(response.promptId), `unknown prompt ${response.promptId}`);
    assert.ok(response.revisions.length >= 1);
    response.revisions.forEach((rev, i) => {
      const expectedSupersedes = i === 0 ? null : response.revisions[i - 1].revisionId;
      assert.equal(rev.supersedesRevisionId, expectedSupersedes);
      assert.ok(rev.text.trim().length > 0);
    });
  }
});

test('the demo exercises the states a demo exists to show', () => {
  const bundle = loadBundle();
  const multiRevision = bundle.responses.filter((r) => r.revisions.length > 1);
  assert.ok(multiRevision.length >= 1, 'at least one response should carry revision history');
  const sources = new Set(bundle.responses.flatMap((r) => r.revisions.map((rev) => rev.source)));
  assert.ok(sources.size >= 2, 'capture sources should be mixed');
  assert.ok(bundle.drafts.length >= 1, 'an uncommitted draft should be included');

  const record: WolfRecord = {
    recordId: bundle.recordId,
    title: bundle.title,
    subject: bundle.subject,
    packId: bundle.pack.packId,
    packVersion: bundle.pack.packVersion,
    packDigest: bundle.pack.packDigest,
    packSnapshot: bundle.pack.snapshot,
    createdAt: bundle.createdAt,
    updatedAt: bundle.updatedAt,
    status: bundle.status,
    responses: bundle.responses,
    drafts: bundle.drafts,
    lastExportedAt: bundle.provenance.exportedAt,
    appVersion: bundle.provenance.appVersion,
  };
  const progress = computeProgress(bundle.pack.snapshot, record);
  assert.equal(progress.totalPrompts, 12);
  assert.equal(progress.answeredPrompts, 9);
  assert.equal(progress.draftPrompts, 1);
  assert.ok(progress.answeredPrompts < progress.totalPrompts, 'unanswered prompts should remain visible');
});
