import type { DecisionCase, InspectionPlaybook } from '../types.js';

export const cafeDisplayPlaybook: InspectionPlaybook = {
  playbookId: 'cafe-display',
  version: '1.0.0',
  title: 'Customer-facing display inspection',
  summary:
    'Captures the actual display installation, operating condition, ventilation, and customer role before maintenance or replacement decisions are made.',
  assetCategory: 'hospitality.display.customer-facing',
  factPrompts: [
    {
      factKey: 'active_hazard',
      label: 'Is there smoke, a burning smell, visible scorching, liquid intrusion, or unusual heat?',
      kind: 'boolean',
      required: true,
    },
    {
      factKey: 'powers_on',
      label: 'Does the display power on?',
      kind: 'choice',
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'intermittent', label: 'Intermittently' },
        { value: 'no', label: 'No' },
        { value: 'unknown', label: 'Unknown' },
      ],
      required: true,
    },
    {
      factKey: 'rear_safe_to_access',
      label: 'Can the rear exterior be viewed safely after the display is powered off?',
      help: 'Do not move a heavy, unstable, hard-wired, or overhead-mounted display without qualified help.',
      kind: 'boolean',
      required: true,
    },
    {
      factKey: 'model_known',
      label: 'Is the exact manufacturer and model documented?',
      kind: 'boolean',
      required: true,
    },
    {
      factKey: 'multiple_displays',
      label: 'Does the shop operate more than one customer-facing display?',
      kind: 'boolean',
      required: true,
    },
    {
      factKey: 'display_is_operationally_essential',
      label: 'Would losing this display materially disrupt ordering or pickup?',
      kind: 'boolean',
      required: true,
    },
  ],
  hazardRules: [
    {
      ruleId: 'display-hazard-stop',
      label: 'Stop ordinary capture',
      message:
        'Power the display down only if that can be done safely, keep people away from the hazard, and route the inspection to a qualified technician.',
      severity: 'urgent',
      blocksCapture: true,
      when: [{ factKey: 'active_hazard', operator: 'equals', value: true }],
    },
  ],
  captureRequests: [
    {
      requestId: 'customer-view',
      label: 'Customer view',
      instruction:
        'Take one photograph from the normal customer approach showing the display, menu or pickup context, sight lines, and nearby light sources.',
      purpose: 'Records the business function and whether a replacement must preserve visibility, size, or placement.',
      acceptedKinds: ['photo'],
      priority: 'critical',
      safety: 'routine',
      resolves: ['customer_role', 'viewing_distance', 'glare', 'placement_constraints'],
    },
    {
      requestId: 'operating-symptom-video',
      label: 'Operating symptom',
      instruction:
        'Record a short video of startup and the visible failure or normal operation. Include the power indicator and screen without repeatedly cycling power.',
      purpose: 'Separates no-power, backlight, signal, intermittent, and content-path symptoms.',
      acceptedKinds: ['video'],
      priority: 'high',
      safety: 'routine',
      resolves: ['startup_behavior', 'power_indicator', 'visible_symptom'],
    },
    {
      requestId: 'installation-context',
      label: 'Installation and environment',
      instruction:
        'Photograph the complete installation, including wall clearance, mount, nearby heat or steam sources, cable path, and ventilation space.',
      purpose: 'Identifies environmental and access conditions that affect service life and replacement labor.',
      acceptedKinds: ['photo'],
      priority: 'high',
      safety: 'routine',
      resolves: ['mounting', 'clearance', 'heat_exposure', 'steam_exposure', 'cable_access'],
    },
    {
      requestId: 'rear-ventilation',
      label: 'Rear ventilation and dust',
      instruction:
        'After the display is powered off, photograph the rear exterior, ventilation openings, dust condition, and wall clearance. Do not open the housing.',
      purpose: 'Documents preventable thermal loading and the maintenance procedure the installation actually needs.',
      acceptedKinds: ['photo', 'video'],
      priority: 'high',
      safety: 'power_off',
      resolves: ['vent_obstruction', 'dust_load', 'rear_clearance'],
      when: [{ factKey: 'rear_safe_to_access', operator: 'equals', value: true }],
    },
    {
      requestId: 'model-and-label',
      label: 'Model and ratings label',
      instruction:
        'Photograph the manufacturer label, model, serial number, power rating, and any asset tag without opening the housing.',
      purpose: 'Enables manual, parts, recall, service, mounting, and replacement research against the exact unit.',
      acceptedKinds: ['photo'],
      priority: 'normal',
      safety: 'power_off',
      resolves: ['manufacturer', 'model', 'serial', 'power_rating'],
    },
    {
      requestId: 'purchase-and-service-history',
      label: 'Purchase and service history',
      instruction:
        'Attach any purchase record, installation invoice, warranty information, prior service message, or remembered installation date.',
      purpose: 'Supports repair-versus-replacement analysis and identifies whether the failure followed a known maintenance gap.',
      acceptedKinds: ['document', 'photo', 'statement'],
      priority: 'low',
      safety: 'routine',
      resolves: ['age', 'warranty', 'prior_service', 'installed_cost'],
    },
  ],
};

export const cafeDisplayDecisionCase: DecisionCase = {
  decisionCaseId: 'cafe-display-durable-path',
  title: 'Durable customer-display paths',
  context:
    'Relative values are placeholders until the exact display, local service quote, customer role, downtime cost, and installation constraints are known.',
  metrics: [
    {
      metricId: 'cash_now',
      label: 'Immediate cash',
      description: 'Relative near-term expenditure.',
      direction: 'minimize',
      weight: 0.2,
      unit: 'relative 1–5',
    },
    {
      metricId: 'five_year_burden',
      label: 'Five-year operating burden',
      description: 'Expected cleaning, repair, sourcing, owner attention, and repeat installation work.',
      direction: 'minimize',
      weight: 0.25,
      unit: 'relative 1–5',
    },
    {
      metricId: 'downtime',
      label: 'Ordering disruption',
      description: 'Relative risk and duration of customer-facing downtime.',
      direction: 'minimize',
      weight: 0.15,
      unit: 'relative 1–5',
    },
    {
      metricId: 'customer_continuity',
      label: 'Customer continuity',
      description: 'Ability to preserve the current ordering and pickup experience.',
      direction: 'maximize',
      weight: 0.15,
      unit: 'relative 1–5',
    },
    {
      metricId: 'standardization',
      label: 'Standardization benefit',
      description: 'Reduction in future maintenance, mounting, content, and spare-device branches.',
      direction: 'maximize',
      weight: 0.15,
      unit: 'relative 1–5',
    },
    {
      metricId: 'reversibility',
      label: 'Reversibility',
      description: 'Ability to change course without abandoning substantial work.',
      direction: 'maximize',
      weight: 0.1,
      unit: 'relative 1–5',
    },
  ],
  options: [
    {
      optionId: 'clean-service-and-sop',
      label: 'Clean, service, and schedule the current display',
      summary: 'Restore the present installation where diagnosis shows a serviceable unit and prevent recurrence with a scheduled procedure.',
      metricValues: {
        cash_now: 1,
        five_year_burden: 3,
        downtime: 2,
        customer_continuity: 5,
        standardization: 1,
        reversibility: 5,
      },
      evidenceConfidence: 0.45,
      benefits: ['Lowest disruption to the current customer experience', 'Converts the maintenance failure into a repeatable procedure'],
      burdens: ['May preserve an aging or difficult-to-source unit', 'Requires diagnosis before cleaning is treated as a repair'],
      assumptions: ['The display remains serviceable and the symptom is not a terminal panel or board failure'],
      reopeningTriggers: ['Failure returns', 'Parts are unavailable', 'Service cost approaches replacement cost'],
    },
    {
      optionId: 'repair-current',
      label: 'Repair the current display',
      summary: 'Use a documented repair path when the exact model, failed assembly, parts availability, and labor are known.',
      metricValues: {
        cash_now: 2,
        five_year_burden: 3,
        downtime: 3,
        customer_continuity: 5,
        standardization: 1,
        reversibility: 4,
      },
      evidenceConfidence: 0.4,
      benefits: ['Preserves mounting, content, and visual fit', 'May avoid unnecessary replacement'],
      burdens: ['Unknown residual life', 'Parts and technician availability may dominate cost'],
      assumptions: ['A qualified diagnosis identifies a repairable assembly'],
      reopeningTriggers: ['Quote exceeds the stored replacement threshold', 'Warranty is unavailable', 'A second failure occurs'],
    },
    {
      optionId: 'replace-equivalent-with-sop',
      label: 'Replace with a documented equivalent and maintenance SOP',
      summary: 'Replace the failed asset while preserving its customer role, then schedule ventilation and dust inspection.',
      metricValues: {
        cash_now: 3,
        five_year_burden: 2,
        downtime: 2,
        customer_continuity: 5,
        standardization: 3,
        reversibility: 3,
      },
      evidenceConfidence: 0.55,
      benefits: ['Known support life and warranty', 'Opportunity to correct clearance, mounting, and maintenance access'],
      burdens: ['Capital and installation work', 'Content or mount migration may be required'],
      assumptions: ['The display is operationally useful enough to preserve'],
      reopeningTriggers: ['Customer evidence shows the screen is not useful', 'Mounting or content migration cost is disproportionate'],
    },
    {
      optionId: 'standardize-display-system',
      label: 'Standardize the customer-display system',
      summary: 'Adopt one supported display, mount, content path, maintenance procedure, and spare strategy across the shop.',
      metricValues: {
        cash_now: 5,
        five_year_burden: 1,
        downtime: 4,
        customer_continuity: 5,
        standardization: 5,
        reversibility: 1,
      },
      evidenceConfidence: 0.35,
      benefits: ['Smallest long-run support tree', 'Predictable replacement and content procedure'],
      burdens: ['Largest capital and implementation burden', 'May replace functioning equipment early'],
      assumptions: ['More than one display or content path creates recurring maintenance friction'],
      reopeningTriggers: ['The shop has only one isolated display', 'The customer role does not justify the investment'],
    },
    {
      optionId: 'remove-display-dependency',
      label: 'Remove the operational dependency on the display',
      summary: 'Shift essential ordering information to durable static or other existing surfaces, with the screen optional rather than critical.',
      metricValues: {
        cash_now: 2,
        five_year_burden: 1,
        downtime: 1,
        customer_continuity: 3,
        standardization: 4,
        reversibility: 4,
      },
      evidenceConfidence: 0.3,
      benefits: ['Eliminates a single point of operational failure', 'Can reduce ongoing device and content maintenance'],
      burdens: ['May reduce visual flexibility or product discovery', 'Requires customer-flow evidence before changing the experience'],
      assumptions: ['Essential information can be communicated clearly without the screen'],
      reopeningTriggers: ['Ordering confusion increases', 'Retention or conversion evidence favors the display'],
    },
  ],
};
