import type { DecisionCase, InspectionPlaybook } from '../types.js';

export const recessedLightingPlaybook: InspectionPlaybook = {
  playbookId: 'recessed-lighting',
  version: '1.0.0',
  title: 'Recessed-light failure inspection',
  summary:
    'Builds a local model of mixed or discontinued recessed-light components before repair or replacement decisions are made.',
  assetCategory: 'electrical.lighting.recessed',
  factPrompts: [
    {
      factKey: 'active_hazard',
      label: 'Is there smoke, sparking, a burning smell, visible scorching, or unusual heat?',
      help: 'Do not approach or touch the fixture to answer. Use only what is already safely observable.',
      kind: 'boolean',
      required: true,
    },
    {
      factKey: 'fail_together',
      label: 'Do multiple fixtures wink out or flicker together?',
      kind: 'choice',
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No, they fail independently' },
        { value: 'unknown', label: 'Unknown' },
      ],
      required: true,
    },
    {
      factKey: 'dimmer_present',
      label: 'Is the circuit controlled by a dimmer?',
      kind: 'choice',
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
        { value: 'unknown', label: 'Unknown' },
      ],
      required: true,
    },
    {
      factKey: 'changes_with_dimmer',
      label: 'Does the symptom change at a different dimmer position?',
      kind: 'choice',
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
        { value: 'not_applicable', label: 'No dimmer or not applicable' },
        { value: 'unknown', label: 'Unknown' },
      ],
      required: true,
    },
    {
      factKey: 'model_known',
      label: 'Is the exact manufacturer and model documented?',
      kind: 'boolean',
      required: true,
    },
    {
      factKey: 'replacement_being_considered',
      label: 'Is a replacement or standardization path being considered now?',
      kind: 'boolean',
      required: true,
    },
  ],
  hazardRules: [
    {
      ruleId: 'electrical-hazard-stop',
      label: 'Stop ordinary capture',
      message:
        'Do not touch the switch, trim, fixture, or wiring. Isolate the area if needed and route the inspection to a qualified electrician.',
      severity: 'emergency',
      blocksCapture: true,
      when: [{ factKey: 'active_hazard', operator: 'equals', value: true }],
    },
  ],
  captureRequests: [
    {
      requestId: 'room-wide-context',
      label: 'Whole-room fixture map',
      instruction:
        'Take one wide photograph showing the complete ceiling, every recessed fixture, and enough room context to identify each fixture position later.',
      purpose: 'Establishes count, layout, mixed trims, and a stable location map.',
      acceptedKinds: ['photo'],
      priority: 'critical',
      safety: 'routine',
      resolves: ['fixture_count', 'fixture_positions', 'visible_mixed_components'],
    },
    {
      requestId: 'operating-pattern-video',
      label: 'Operating-pattern video',
      instruction:
        'From a safe standing position, record the ceiling while the ordinary wall control is operated through the normal range. Do not touch any fixture.',
      purpose: 'Shows whether failures are simultaneous, independent, delayed, or correlated with dimmer position.',
      acceptedKinds: ['video'],
      priority: 'critical',
      safety: 'routine',
      resolves: ['simultaneous_failure', 'dimmer_correlation', 'delay_pattern'],
    },
    {
      requestId: 'working-failing-comparison',
      label: 'Working and failing fixture comparison',
      instruction:
        'Take close external photographs of one working fixture and one failing fixture from the same angle. Keep the trim and surrounding ceiling visible.',
      purpose: 'Compares trim, lens, discoloration, fit, and visible component differences without disassembly.',
      acceptedKinds: ['photo'],
      priority: 'high',
      safety: 'routine',
      resolves: ['visible_fixture_family', 'heat_discoloration', 'trim_fit'],
    },
    {
      requestId: 'wall-control-face',
      label: 'Wall control',
      instruction:
        'Photograph the front of the switch or dimmer and the surrounding plate. Do not remove the plate.',
      purpose: 'Identifies the control family and whether a shared dimming path is plausible.',
      acceptedKinds: ['photo'],
      priority: 'high',
      safety: 'routine',
      resolves: ['control_type', 'visible_control_model'],
    },
    {
      requestId: 'existing-documents',
      label: 'Existing model evidence',
      instruction:
        'Photograph or attach any old box, invoice, contractor message, spare module, or prior label photograph that identifies either installed brand or model.',
      purpose: 'Separates documented compatibility from visual resemblance or memory.',
      acceptedKinds: ['photo', 'document'],
      priority: 'normal',
      safety: 'routine',
      resolves: ['manufacturer', 'model', 'installation_history'],
    },
    {
      requestId: 'isolated-label-and-connector',
      label: 'Internal label and connector',
      instruction:
        'Have the electrician or qualified contractor photograph the internal model label, connector, driver, mounting arrangement, and housing only after the circuit is safely isolated.',
      purpose: 'Determines electrical and mechanical compatibility when the model is not already documented.',
      acceptedKinds: ['photo', 'video'],
      priority: 'high',
      safety: 'licensed_trade',
      resolves: ['exact_model', 'connector_type', 'driver_configuration', 'mounting_standard'],
      when: [{ factKey: 'model_known', operator: 'equals', value: false }],
    },
    {
      requestId: 'replacement-dimensions',
      label: 'Replacement dimensions',
      instruction:
        'Have the electrician or qualified contractor record nominal diameter, ceiling cutout, housing depth, and available clearance while the circuit is isolated.',
      purpose: 'Prevents a visually plausible replacement from becoming an incompatible purchase or ceiling repair.',
      acceptedKinds: ['photo', 'measurement'],
      priority: 'normal',
      safety: 'licensed_trade',
      resolves: ['cutout_size', 'housing_depth', 'clearance', 'nominal_diameter'],
      when: [{ factKey: 'replacement_being_considered', operator: 'equals', value: true }],
    },
  ],
};

export const recessedLightingDecisionCase: DecisionCase = {
  decisionCaseId: 'recessed-lighting-durable-path',
  title: 'Durable recessed-lighting paths',
  context:
    'Illustrative relative values keep the full option range visible until local quotes, fixture evidence, service history, and electrical diagnosis replace them.',
  metrics: [
    {
      metricId: 'cash_now',
      label: 'Immediate cash',
      description: 'Relative near-term expenditure, where 1 is lowest and 5 is highest.',
      direction: 'minimize',
      weight: 0.2,
      unit: 'relative 1–5',
    },
    {
      metricId: 'five_year_burden',
      label: 'Five-year owner burden',
      description: 'Expected repair visits, sourcing work, complaint handling, and administration.',
      direction: 'minimize',
      weight: 0.25,
      unit: 'relative 1–5',
    },
    {
      metricId: 'recurrence_risk',
      label: 'Recurrence risk',
      description: 'Likelihood that the same decision has to be reconstructed again.',
      direction: 'minimize',
      weight: 0.25,
      unit: 'relative 1–5',
    },
    {
      metricId: 'disruption',
      label: 'Occupant disruption',
      description: 'Relative access, downtime, and installation disruption.',
      direction: 'minimize',
      weight: 0.1,
      unit: 'relative 1–5',
    },
    {
      metricId: 'standardization',
      label: 'Standardization benefit',
      description: 'Reduction in future compatibility and spare-parts branches.',
      direction: 'maximize',
      weight: 0.1,
      unit: 'relative 1–5',
    },
    {
      metricId: 'reversibility',
      label: 'Reversibility',
      description: 'Ability to change course without abandoning substantial work or materials.',
      direction: 'maximize',
      weight: 0.1,
      unit: 'relative 1–5',
    },
  ],
  options: [
    {
      optionId: 'diagnose-shared-path',
      label: 'Diagnose the shared control or circuit first',
      summary: 'Prioritize common-cause diagnosis before purchasing replacement fixtures.',
      metricValues: {
        cash_now: 2,
        five_year_burden: 2,
        recurrence_risk: 1,
        disruption: 2,
        standardization: 1,
        reversibility: 5,
      },
      evidenceConfidence: 0.55,
      benefits: ['Avoids replacing fixtures when the root cause is upstream', 'Preserves all later replacement options'],
      burdens: ['Requires qualified diagnosis', 'May not restore a failed module immediately'],
      assumptions: ['Several symptoms may share a control, connection, or circuit condition'],
      reopeningTriggers: ['Failures are confirmed independent', 'Control and circuit test normally'],
    },
    {
      optionId: 'replace-failed-only',
      label: 'Replace only failed modules',
      summary: 'Use verified compatible current products only where a fixture has failed.',
      metricValues: {
        cash_now: 1,
        five_year_burden: 4,
        recurrence_risk: 4,
        disruption: 1,
        standardization: 1,
        reversibility: 5,
      },
      evidenceConfidence: 0.45,
      benefits: ['Lowest immediate expenditure', 'Least immediate disruption'],
      burdens: ['Repeated sourcing and contractor visits', 'Potential mixed appearance and compatibility drift'],
      assumptions: ['A documented compatible product exists', 'Failures are independent'],
      reopeningTriggers: ['Another fixture fails', 'Compatibility cannot be documented', 'Labor exceeds material cost'],
    },
    {
      optionId: 'replace-and-stock-spares',
      label: 'Replace failures and retain verified spares',
      summary: 'Preserve the current installation while reducing future procurement delay.',
      metricValues: {
        cash_now: 2,
        five_year_burden: 3,
        recurrence_risk: 3,
        disruption: 1,
        standardization: 2,
        reversibility: 4,
      },
      evidenceConfidence: 0.5,
      benefits: ['Faster response to the next failure', 'Preserves visual consistency if the match is verified'],
      burdens: ['Ties cash to inventory', 'Spares may age before use'],
      assumptions: ['The compatible replacement is likely to remain appropriate for the installed base'],
      reopeningTriggers: ['Failure rate accelerates', 'Stored spares show incompatibility', 'A shared electrical cause is found'],
    },
    {
      optionId: 'standardize-room',
      label: 'Standardize one room or circuit',
      summary: 'Replace the local mixed set with one documented current system.',
      metricValues: {
        cash_now: 4,
        five_year_burden: 1,
        recurrence_risk: 1,
        disruption: 3,
        standardization: 4,
        reversibility: 2,
      },
      evidenceConfidence: 0.55,
      benefits: ['Consistent light quality', 'One documented replacement and spare path'],
      burdens: ['Higher immediate capital', 'Functioning components may be retired early'],
      assumptions: ['Several fixtures in the same area are aging, mixed, or unavailable'],
      reopeningTriggers: ['Upstream diagnosis resolves the failures', 'A compatible low-burden replacement becomes available'],
    },
    {
      optionId: 'stage-property-standardization',
      label: 'Stage property-wide standardization',
      summary: 'Adopt one current standard and replace by planned area or failure threshold.',
      metricValues: {
        cash_now: 5,
        five_year_burden: 1,
        recurrence_risk: 1,
        disruption: 5,
        standardization: 5,
        reversibility: 1,
      },
      evidenceConfidence: 0.35,
      benefits: ['Smallest long-run compatibility tree', 'Predictable procedures and spares'],
      burdens: ['Largest capital and coordination requirement', 'Risk of premature replacement'],
      assumptions: ['The mixed and discontinued condition recurs across multiple units'],
      reopeningTriggers: ['Failure history remains isolated to one room', 'Capital timing changes', 'A shared upstream defect is found'],
    },
  ],
};
